### ISSUE TITLE
Error UndefVarError: `mpiexec_path` not defined

### ISSUE THREAD

**Issue by lduits** [fverdugo/XM_40017#16]
When trying to run MPI code, an error shows up: `mpiexec_path` not defined. Therefore, it is not possible to run MPI code from the terminal as described in the section "Running MPI code".

![mpiexec_path not defined](https://github.com/fverdugo/XM_40017/assets/78210196/7e3ed057-9556-4379-8b72-9441c347bf25)

**Comment by fverdugo** [comment]
Hi @lduits 

Thanks for reporting this!

I can reproduce the issue. The tutorial was written (last year) for a previous version of MPI.jl. Newer versions of MPI.jl have removed the MPI.mpiexec_path variable. I will update the tutorial to the new version. (by removing this part that is not longer valid).
