### ISSUE TITLE
Some of my thoughts on Latency hiding

### ISSUE THREAD

**Issue by ezrannetttty** [fverdugo/XM_40017#29]
https://github.com/fverdugo/XM_40017/blob/26afa1d3c71e169189620f7435bd02b66b8f4499/notebooks/jacobi_method.ipynb#L641

May I ask if what you are trying to convey is in fact: "we are hiding communication latency by overlapping it with `computation` that we need to do anyway"?

**Comment by fverdugo** [comment]
Dear @ezrannetttty,

yes, this is indeed a typo. 

with **communication** that we need to do anyway -> with **computation** that we need to do anyway.

Feel free to open a PR.
